repos:
  # Python форматирование и линтинг
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        types: [python]

  # Сортировка импортов
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        types: [python]

  # Линтинг кода
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]
        types: [python]

  # Проверка безопасности
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, brains/, evo/, tasks/, api/]
        types: [python]

  - repo: local
    hooks:
      - id: safety-check
        name: Safety
        entry: python scripts/safety_check.py
        language: system
        pass_filenames: false
        always_run: true

  # Frontend: ESLint
  - repo: local
    hooks:
      - id: frontend-lint
        name: ESLint
        entry: python scripts/frontend_lint.py
        language: system
        types: [file]
        files: ^web/frontend/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false
        always_run: true

  # Frontend: Prettier
  - repo: local
    hooks:
      - id: frontend-prettier
        name: Prettier
        entry: python scripts/frontend_prettier.py
        language: system
        types: [file]
        files: ^web/frontend/.*\.(ts|tsx|js|jsx|json|css|md|html)$
        pass_filenames: false
        always_run: true

  # Frontend: TypeScript проверка
  - repo: local
    hooks:
      - id: frontend-tsc
        name: TypeScript
        entry: python scripts/frontend_tsc.py
        language: system
        types: [file]
        files: ^web/frontend/.*\.(ts|tsx)$
        pass_filenames: false
        always_run: true

  # Frontend: Тесты
  - repo: local
    hooks:
      - id: frontend-test
        name: Frontend Tests
        entry: python scripts/frontend_test.py
        language: system
        types: [file]
        files: ^web/frontend/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false
        always_run: true

  # Базовые проверки
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
